CREATE TABLE USERS (
    uid INT PRIMARY KEY,
    email VARCHAR(300),
    name VARCHAR(300),
    role VARCHAR(300)
);

CREATE TABLE NON_GSUITE_USERS (
    uid INT,
    salt BYTEA,
    pw BYTEA,
    FOREIGN KEY (uid) REFERENCES USERS(uid)
);

CREATE TABLE GSUITE_USERS (
    uid INT,
    googleID INT,
    FOREIGN KEY (uid) REFERENCES USERS(uid)
)